In [1]:
import numpy as np
matrix = []
baris = 0
kolom = 0

In [2]:
def deklarasi_matrix():
    global matrix
    global baris
    global kolom
    #deklarasi matrix sementara
    baris = int(input("Masukkan Jumlah Baris : "))
    kolom = int(input("Masukkan Jumlah Kolom : "))
    matrix = np.zeros((baris, kolom))
    print("Matrix sementara : ")
    print(matrix)
    main()

In [3]:
def input_matrix():
    global matrix
    global baris
    global kolom
    #input data ke matrix
    for x in range(baris):
        for y in range(kolom):
            print("Masukkan Nilai Baris-", x, " Kolom-", y, " : ")
            a = float(input())
            matrix[x][y] = a
    main()

In [4]:
def invers_matrix():
    print("Determinant Matrix : ", np.linalg.det(matrix))
    print("Invers Matrix : ")
    hasil = np.linalg.inv(matrix)
    print(hasil)
    main()

In [5]:
def menu():
    print("Pilih Operasi : ")
    print("1. Deklarasi Ukuran Matrix")
    print("2. Masukkan Data Matrix")
    print("3. Kosongkan Matrix")
    print("4. Lihat Data Matrix")
    print("5. Invers Matrix")

In [6]:
def main():
    menu()
    global matrix
    pilihan = int(input("Masukkan Pilihan Operasi : "))
    if pilihan == 1:
        deklarasi_matrix()
    elif pilihan == 2:
        input_matrix()
    elif pilihan == 3:
        matrix = np.zeros((2, 2))
        main()
    elif pilihan == 4:
        print("Matrix Baru : ")
        print(matrix)
        main()
    elif pilihan == 5:
        invers_matrix()
    else :
        print("Pilihan Tidak Tersedia")

In [8]:
main()

Pilih Operasi : 
1. Deklarasi Ukuran Matrix
2. Masukkan Data Matrix
3. Kosongkan Matrix
4. Lihat Data Matrix
5. Invers Matrix
Masukkan Pilihan Operasi : 1
Masukkan Jumlah Baris : 3
Masukkan Jumlah Kolom : 3
Matrix sementara : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Pilih Operasi : 
1. Deklarasi Ukuran Matrix
2. Masukkan Data Matrix
3. Kosongkan Matrix
4. Lihat Data Matrix
5. Invers Matrix
Masukkan Pilihan Operasi : 2
Masukkan Nilai Baris- 0  Kolom- 0  : 
1
Masukkan Nilai Baris- 0  Kolom- 1  : 
2
Masukkan Nilai Baris- 0  Kolom- 2  : 
3
Masukkan Nilai Baris- 1  Kolom- 0  : 
0
Masukkan Nilai Baris- 1  Kolom- 1  : 
1
Masukkan Nilai Baris- 1  Kolom- 2  : 
4
Masukkan Nilai Baris- 2  Kolom- 0  : 
5
Masukkan Nilai Baris- 2  Kolom- 1  : 
6
Masukkan Nilai Baris- 2  Kolom- 2  : 
0
Pilih Operasi : 
1. Deklarasi Ukuran Matrix
2. Masukkan Data Matrix
3. Kosongkan Matrix
4. Lihat Data Matrix
5. Invers Matrix
Masukkan Pilihan Operasi : 5
Determinant Matrix :  0.9999999999999964
Invers Matrix : 
[[-24.  

In [ ]:
a = "Ini Variable Global"
b = "Ini Bisa Dipakai Sama Semua Function"

In [ ]:
def coba():
    global b
    b = "Ini Variable b yg Baru"
    a = "Ini Punya Si Coba"
    c = "Ini Variable Lokal"
    print(a)
    print(c)
    print(b)

In [ ]:
print(a)
print(b)
print(c)

In [ ]:
coba()
print(b)