In [3]:
import numpy as np

#deklarasi matrix sementara
baris = int(input("Masukkan Jumlah Baris : "))
kolom = int(input("Masukkan Jumlah Kolom : "))
matrix = np.zeros((baris, kolom))
print("Matrix sementara : ")
print(matrix)

#input data ke matrix
for x in range(baris):
    for y in range(kolom):
        print("Masukkan Nilai Baris-", x, " Kolom-", y, " : ")
        a = float(input())
        matrix[x][y] = a

print("Matrix baru : ")
print(matrix)

print("Determinant Matrix : ", np.linalg.det(matrix))
print("Invers Matrix : ")
hasil = np.linalg.inv(matrix)
print(hasil)

Masukkan Jumlah Baris : 3
Masukkan Jumlah Kolom : 3
Matrix sementara : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Masukkan Nilai Baris- 0  Kolom- 0  : 
1
Masukkan Nilai Baris- 0  Kolom- 1  : 
2
Masukkan Nilai Baris- 0  Kolom- 2  : 
3
Masukkan Nilai Baris- 1  Kolom- 0  : 
0
Masukkan Nilai Baris- 1  Kolom- 1  : 
1
Masukkan Nilai Baris- 1  Kolom- 2  : 
4
Masukkan Nilai Baris- 2  Kolom- 0  : 
5
Masukkan Nilai Baris- 2  Kolom- 1  : 
6
Masukkan Nilai Baris- 2  Kolom- 2  : 
0
Matrix baru : 
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]
Determinant Matrix :  0.9999999999999964
Invers Matrix : 
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
